pull_request_rules:
  - name: label scala-steward's PRs
    conditions:
      - author=filosganga-scala-steward

    actions:
      label:
        add:
          - dependencies
        remove: []
  - name: merge scala-steward's PRs
    conditions:
      - author=filosganga-scala-steward
      - status-success=unit-tests-report
      - status-success=integration-tests-report
    actions:
      merge:
        method: merge
