name: ci

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/heads/release/' ) }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DYNAMODB_ENDPOINT: "http://localhost:8000"
      AWS_REGION: "eu-west-1"
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    services:
      dynamodb:
        image: amazon/dynamodb-local:1.21.0
        ports:
          - "8000:8000"

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Restore dependencies
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-${{ hashFiles('**/*.sbt', 'project/build.properties') }}
      - name: Update dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: sbt +update
      - name: Cache dependencies
        uses: actions/cache/save@v4
        if: steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-${{ hashFiles('**/*.sbt', 'project/build.properties') }}
      - run: sbt "+scalafmtCheckAll;+headerCheckAll;+Test/compile;+scalafixAll --check;+test"
      - uses: alehechka/upload-tartifact@v2
        with:
          name: targets
          path: "**/target/**"
          if-no-files-found: error
          retention-days: 1

  publish:
    if: github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/heads/release/' )
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Restore dependencies
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-${{ hashFiles('**/*.sbt', 'project/build.properties') }}
      - uses: alehechka/download-tartifact@v2
        with:
          name: targets
      - uses: scalacenter/sbt-dependency-submission@v3
      - run: echo $PGP_SECRET | base64 -d | gpg --import
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
      - run: sbt "+publishSigned"
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASS: ${{ secrets.SONATYPE_PASS }}
